# Generated by Django 5.2.6 on 2025-09-09 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_table_alter_product_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='addresses',
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customers',
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.AlterModelTable(
            name='supplier',
            table='suppliers',
        ),
    ]
